# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: ViệtTíx Linux
description: "Hệ điều hành được làm bởi người Việt, cho người Việt."
baseurl: "/"
url: "https://viettixlinux.pages.dev/"
lang: vi-VN
repository_url: "https://github.com/viettixlinux"
download_url: "/download.html"
logo_path: "/assets/img/logo.svg"
languages: ["vi", "en"]
exclude_from_localizations: ["assets", "favicon.ico"]
namespace:     vi
permalink:      /vi/
permalink_en:   /en/

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-multiple-languages-plugin

include:
  - assets


exclude:
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
